universe = vanilla
executable = finetune_vqa.sh
log    = ft_$(Cluster).log
output = ft_$(Cluster).out
error  = ft_$(Cluster).err

request_cpus = 16
request_memory = 128GB
request_disk = 100GB
request_gpus = 2
requirements = (CUDAGlobalMemoryMb >= 70000)
rank = (Machine == "bhaskargpu4000.chtc.wisc.edu") * 1000
+WantStagingMount = true

transfer_input_files = ../configs/finetune_surgvu_vqa.yaml, finetune_inner.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
queue
